### PR TITLE
Increase font-weight for better readability. Fixes #119

### LINKED ISSUE #119: fix the font weight and color on the site
The sites is highly unreadable right now because such light font with no contrast color.

screenshot 2017-04-26 10 39 21

### PR DESCRIPTION
**Pull request by chinchang**
Before:
screenshot 2017-04-26 10 44 45

After:
screenshot 2017-04-26 10 45 16

### CODE REVIEW

**Comment by thierryk** [comment]
`400` is the same as the keyword `normal`, so it may be better to simply *omit* this value in the declaration&mdash;since `normal` is the initial value.

Could you replace:

```css
font: 400 16px/1.55 "Helvetica Neue", Helvetica, Arial, sans-serif; /* 1 */
```

with:

```css
font: 16px/1.55 "Helvetica Neue", Helvetica, Arial, sans-serif; /* 1 */
```

Thank you very much for this PR, I should have done that myself long time ago...

**Comment by chinchang** [comment]
@thierryk Done! And you are welcome. Glad to help.

**Comment by vikrantnegi** [comment]
When will this merge be visible on the site?
I'm still seeing the old CSS there.

**Comment by thierryk** [comment]
@src-code should take care of that "soon" (things have changed since I left Yahoo! I have no clue how deployment is done today).

**Comment by thierryk** [comment]
It's done! Thanks @src-code

**Pull request merged**
